name: Deployment Workflow
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Get Code from github
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npx eslint src/ --ext .js,.jsx,.ts,.tsx --max-warnings 0
      - name: Upload Lint Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: |
            eslint-report.json
            *.log
          retention-days: 7

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Get Code from github
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests with Coverage
        run: npm run test:coverage
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            coverage/
            test-results.xml
          retention-days: 30
      - name: Upload Test Outcome
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-outcome
          path: |
            coverage/lcov-report/
            *.log
          retention-days: 7
      - name: Notify Test Completion
        run: echo "Tests completed successfully!"

  build:
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Get Code from github
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
      - name: Notify Build Completion
        run: echo "Build completed and artifacts uploaded!"

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/
      - name: List Artifact Contents
        run: ls -la build/
      - name: Deploy Project
        run: echo "Deploying project..."
      - name: Notify Deployment Completion
        run: echo "Deployment completed successfully!"
