name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: 'true'

      - name: Output information
        run: "Cache used: ${{ steps.cache-deps.outputs.used-cache }}"

      - name: Run Linter
        run: npm run lint

  test:   # <-- aligned properly with lint
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dependencies
        uses: ./.github/actions/cached-deps
      - name: Run Tests
        run: npm test

  build:  # <-- aligned properly with lint
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dependencies
        uses: ./.github/actions/cached-deps
      - name: Build Project
        run: npm run build

  deploy: # <-- aligned properly with lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploying application..."
