name: Matrix CI
on: workflow_dispatch
jobs:
    build:
        continue-on-error: true
        strategy:
          matrix:
            node-version: [14, 16, 18]
            operating-system: [ubuntu-20.04, windows-2022]
            include:
                - node-version: 20
                  operating-system: ubuntu-22.04
            exclude:
                - node-version: 14
                  operating-system: windows-2022
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code from github
              uses: actions/checkout@v4
            - name: install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build