name: Output Workflow
on: [workflow_dispatch]
jobs:
    info:
        runs-on: ubuntu-24.04
        steps:
           - name: Output Information
             run: echo "${{ github.workflow }} workflow is running on ${{ github.event_name }} event. ${{ toJson(github) }} triggered this workflow."